#!/usr/bin/env bash
NUM=01
CLASS=111
NAME="exam${NUM}-${CLASS}"
PDFNAME="exam${NUM}-${CLASS}-V2"
PDFDIR=../pdf/
FILE="$NAME.tex"
texi2pdf $FILE 

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf/${PDFNAME}.pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
rm -fr *.out
