#!/usr/bin/env bash
CLASS=116
SECTION=E1B
NAME="syllabus-${CLASS}-${SECTION}"
PDFDIR=../pdf/
FILE="$NAME.tex"

texi2pdf $FILE

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
rm -fr *.out
