#!/usr/bin/env bash
NUM=02
CLASS=122
NAME="exam${NUM}-${CLASS}"
NAME2="exam${NUM}-${CLASS}"
PDFDIR=../pdf/
FILE="$NAME.tex"
FILE2="$NAME-solns.tex"
texi2pdf $FILE 
#texi2pdf $FILE2

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf
#mv $NAME-solns.pdf ../pdf

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
rm -fr *.out
