#!/usr/bin/env bash
NUM=final
CLASS=161
NAME="schedule-161"
PDFDIR=../pdf/
FILE="${NAME}.tex"

latexmk -pdf ${FILE}
#texi2pdf $FILE
#texi2pdf "${NAME}-solns.tex"

if [ ! -d ../pdf ]; then
    mkdir ../pdf
fi

mv $NAME.pdf ../pdf
#mv "${NAME}-solns.pdf" ../pdf


#rm -fr *.log
#rm -fr *.aux
#rm -fr *.bbl
#rm -fr *.blg
#rm -fr *.out
latexmk -C
rm -fr *~

