#!/usr/bin/env bash
NUM=02
CLASS=170
NAME="final${NUM}-${CLASS}"
PDFDIR=../../pdf/
FILE="$NAME.tex"
texi2pdf $FILE 


if [ ! -d ${PDFDIR} ]; then
    mkdir ${PDFDIR}
fi

mv $NAME.pdf ${PDFDIR}

rm -fr *.log
rm -fr *.aux
rm -fr *.bbl
rm -fr *.blg
rm -fr *~
rm -fr *.out
